In [0]:
import pandas as pd
import numpy as np
import keras
from keras.models import Model
from keras import optimizers
from keras.layers import *
from keras.layers import Input, Dense


In [0]:
import io
from google.colab import files
uploaded = files.upload()
df_train = pd.read_csv(io.BytesIO(uploaded['train.csv']))
df_train.head()

Saving train.csv to train (2).csv


label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0      1       0       0       0  ...         0         0         0         0
1      0       0       0       0  ...         0         0         0         0
2      1       0       0       0  ...         0         0         0         0
3      4       0       0       0  ...         0         0         0         0
4      0       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [0]:
df_train.shape

(42000, 785)

### Splitting the data into Train and Test

In [0]:
X = df_train.drop('label',1)
y = df_train['label']
from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,random_state=32)
Xtrain.shape,ytrain.shape

((31500, 784), (31500,))

## Noramlising the data as the range of the data is from 0 to 255. To handle the grayscale illumination

In [0]:
Xtrain /= 255

In [0]:
#Xtrain.head()

pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
11665     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
18881     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
29147     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
41560     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
40680     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0

[5 rows x 784 columns]

## Reshaping it to 3D matrix and also 28X28X1 =784

In [0]:
Xtrain =Xtrain.values.reshape(Xtrain.shape[0], 28, 28, 1)



In [0]:
Xtrain

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

## Converting y into One hot encoded labels

In [0]:
%tensorflow_version 1.x 
from keras.utils.np_utils import to_categorical 

In [0]:
ytrain = to_categorical(ytrain, num_classes = 10)


In [0]:
ytrain


array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
ytrain[5]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

## Steps to Follow:
1.  Simple Neural Network with 4 Layers
2. Assign Value to Each Hidden Layers
3.  Choose Activation Function : Relu,Sigmoid,Softmax
4. Multiclass problem and finding out which class to output we have to convert it into a probablistic approach.

In [0]:
n_input = 784 
n_hidden_1 = 300
n_hidden_2 = 100
n_hidden_3 = 100
n_hidden_4 = 200
num_digits = 10

There are 6 layers for our simple neural network as we can see . Input ,Output and 4 Hidden Layers

Lets Start feeding each layer starting from the input

In [0]:
inp  = (28,28,1)

In [0]:
inp

<tf.Tensor 'input_2:0' shape=(?, 784) dtype=float32>

In [0]:

x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(inp)

ValueError: ignored

In [0]:
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)


In [0]:
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)


In [0]:
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)

In [0]:
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

In [0]:
model = Model(inp, output)
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 784)               0         
_________________________________________________________________
Hidden_Layer_1 (Dense)       (None, 300)               235500    
_________________________________________________________________
Hidden_Layer_2 (Dense)       (None, 100)               30100     
_________________________________________________________________
Hidden_Layer_3 (Dense)       (None, 100)               10100     
_________________________________________________________________
Hidden_Layer_4 (Dense)       (None, 200)               20200     
_________________________________________________________________
Output_Layer (Dense)         (None, 10)                2010      
Total params: 297,910
Trainable params: 297,910
Non-trainable params: 0
_____________________________________________________

## Optimisation of the model using gradient descent and Hyper parameter Tuning

In [0]:
from keras.optimizers import SGD


1. Learning Rate or eeta value =0.01
2. Momemtum as 0.9 (it can range from 0 to 1)

In [0]:
sgd = SGD(lr=0.01, momentum=0.9, nesterov=True)

In [0]:
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

In [0]:
ytest = to_categorical(ytest,num_classes=10)

In [0]:
Xtest /= 255

In [0]:
Xtest =Xtest.values.reshape(Xtest.shape[0], 28, 28, 1)


In [0]:
hist = model.fit(x=Xtrain, y=ytrain,
                     batch_size = 100,
                     epochs = 20,
                     verbose = 2
                     )